# GitHub Copilot Setup Steps
# Pre-installs dependencies for GitHub Copilot's ephemeral development environment
# See: https://docs.github.com/en/enterprise-cloud@latest/copilot/customizing-copilot/customizing-the-development-environment-for-copilot-coding-agent

steps:
  # Install Node.js LTS version
  - name: Setup Node.js
    uses: actions/setup-node@v4
    with:
      node-version: 'lts/*'
      cache: 'npm'
  
  # Install npm dependencies if package.json exists
  - name: Install dependencies
    run: |
      if [ -f "package.json" ]; then
        npm ci || npm install
      else
        echo "No package.json found, skipping npm install"
      fi
    shell: bash
  
  # Install PostgreSQL for testing (optional, based on project needs)
  - name: Setup PostgreSQL
    uses: ikalnytskyi/action-setup-postgres@v6
    with:
      username: testuser
      password: testpass
      database: testdb
